# For more information: https://laravel.com/docs/sail
version: '3'
services:
    redis.test:
        build:
            context: ./docker/7.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                CHANGE_SOURCE: ${CHANGE_SOURCE}
        image: sail-7.4/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            # - selenium
    # selenium:
    #     image: 'selenium/standalone-chrome'
    #     volumes:
    #         - '/dev/shm:/dev/shm'
    #     networks:
    #         - sail
    #     depends_on:
    #         - laravel.test
    mysql:
        image: 'mysql:latest'
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './docker/data/sailmysql:/var/lib/mysql'
        networks:
            - sail
    redis:
        # image: 'redis:alpine'
        image: 'redislabs/rebloom:latest'
        ports:
            - '${REDIS_PORT}:6379'
        volumes:
            - './docker/data/sailredis:/data'
        networks:
            - sail
    # memcached:
    #     image: 'memcached:alpine'
    #     ports:
    #         - '11211:11211'
    #     networks:
    #         - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - sail
    laravel-echo-server:
        build:
            context: ./docker/laravel-echo-server
            dockerfile: Dockerfile
            args:
                - CHANGE_SOURCE=${CHANGE_SOURCE}
        volumes:
            - ./docker/laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
        ports:
            - "${LARAVEL_ECHO_SERVER_PORT}:6001"
        depends_on:
            - redis
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
